const PRODUCTS = [
  {
    "title": "Круглый бассейн IPOOLGO, диаметр 2,44 м",
    "price": 80000,
    "old_price": null,
    "article": "R-244",
    "category": "Круглые бассейны",
    "image": "assets/ipoolgoo_best/round_premium_01.webp",
    "gallery": [
      "assets/ipoolgoo_best/round_premium_01.webp",
      "assets/ipoolgoo_best/round_premium_02.webp",
      "assets/ipoolgoo_best/round_premium_03.webp",
      "assets/ipoolgoo_best/round_premium_04.webp",
      "assets/ipoolgoo_best/round_premium_05.webp",
      "assets/ipoolgoo_best/round_premium_06.webp",
      "assets/ipoolgoo_best/round_premium_07.webp",
      "assets/ipoolgoo_best/round_premium_08.webp",
      "assets/ipoolgoo_best/round_premium_09.webp",
      "assets/ipoolgoo_best/round_premium_10.webp"
    ],
    "size": "Ø 2,44 м",
    "form": "Круглая",
    "depth": "на выбор: 1 м / 1.1 м / 1.2 м / 1.3 м / 1.6 м / 1.7 м / 1.8 м",
    "desc": "Круглый бассейн IPOOLGO диаметром Ø 2,44 м — удобное решение для частного дома, дачи или зоны отдыха. Круглая форма равномерно распределяет давление воды на стенки, поэтому чаша устойчиво держит форму при активном купании. Материал ПВХ по технологии Drop Stitch делает борта плотными и жёсткими, а установку можно выполнить без капитального строительства. Цена от 80 000 ₸.",
    "features": [
      "ПВХ по технологии Drop Stitch — плотные борта и устойчивая форма чаши",
      "Глубина на выбор: 1 м, 1.1 м, 1.2 м, 1.3 м, 1.6 м, 1.7 м, 1.8 м",
      "Можно установить на ровную площадку во дворе, на даче или рядом с террасой",
      "Подключается фильтрация для поддержания чистоты воды",
      "Ремкомплект и консультация по установке доступны при заказе",
      "Доставка по Казахстану и быстрый заказ через WhatsApp"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Круглый бассейн IPOOLGO, диаметр 3,05 м",
    "price": 100000,
    "old_price": null,
    "article": "R-305",
    "category": "Круглые бассейны",
    "image": "assets/ipoolgoo_best/round_premium_02.webp",
    "gallery": [
      "assets/ipoolgoo_best/round_premium_02.webp",
      "assets/ipoolgoo_best/round_premium_03.webp",
      "assets/ipoolgoo_best/round_premium_04.webp",
      "assets/ipoolgoo_best/round_premium_05.webp",
      "assets/ipoolgoo_best/round_premium_06.webp",
      "assets/ipoolgoo_best/round_premium_07.webp",
      "assets/ipoolgoo_best/round_premium_08.webp",
      "assets/ipoolgoo_best/round_premium_09.webp",
      "assets/ipoolgoo_best/round_premium_10.webp",
      "assets/ipoolgoo_best/round_premium_01.webp"
    ],
    "size": "Ø 3,05 м",
    "form": "Круглая",
    "depth": "на выбор: 1 м / 1.1 м / 1.2 м / 1.3 м / 1.6 м / 1.7 м / 1.8 м",
    "desc": "Круглый бассейн IPOOLGO диаметром Ø 3,05 м — удобное решение для частного дома, дачи или зоны отдыха. Круглая форма равномерно распределяет давление воды на стенки, поэтому чаша устойчиво держит форму при активном купании. Материал ПВХ по технологии Drop Stitch делает борта плотными и жёсткими, а установку можно выполнить без капитального строительства. Цена от 100 000 ₸.",
    "features": [
      "ПВХ по технологии Drop Stitch — плотные борта и устойчивая форма чаши",
      "Глубина на выбор: 1 м, 1.1 м, 1.2 м, 1.3 м, 1.6 м, 1.7 м, 1.8 м",
      "Можно установить на ровную площадку во дворе, на даче или рядом с террасой",
      "Подключается фильтрация для поддержания чистоты воды",
      "Ремкомплект и консультация по установке доступны при заказе",
      "Доставка по Казахстану и быстрый заказ через WhatsApp"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Круглый бассейн IPOOLGO, диаметр 3,66 м",
    "price": 140000,
    "old_price": null,
    "article": "R-366",
    "category": "Круглые бассейны",
    "image": "assets/ipoolgoo_best/round_premium_03.webp",
    "gallery": [
      "assets/ipoolgoo_best/round_premium_03.webp",
      "assets/ipoolgoo_best/round_premium_04.webp",
      "assets/ipoolgoo_best/round_premium_05.webp",
      "assets/ipoolgoo_best/round_premium_06.webp",
      "assets/ipoolgoo_best/round_premium_07.webp",
      "assets/ipoolgoo_best/round_premium_08.webp",
      "assets/ipoolgoo_best/round_premium_09.webp",
      "assets/ipoolgoo_best/round_premium_10.webp",
      "assets/ipoolgoo_best/round_premium_01.webp",
      "assets/ipoolgoo_best/round_premium_02.webp"
    ],
    "size": "Ø 3,66 м",
    "form": "Круглая",
    "depth": "на выбор: 1 м / 1.1 м / 1.2 м / 1.3 м / 1.6 м / 1.7 м / 1.8 м",
    "desc": "Круглый бассейн IPOOLGO диаметром Ø 3,66 м — удобное решение для частного дома, дачи или зоны отдыха. Круглая форма равномерно распределяет давление воды на стенки, поэтому чаша устойчиво держит форму при активном купании. Материал ПВХ по технологии Drop Stitch делает борта плотными и жёсткими, а установку можно выполнить без капитального строительства. Цена от 140 000 ₸.",
    "features": [
      "ПВХ по технологии Drop Stitch — плотные борта и устойчивая форма чаши",
      "Глубина на выбор: 1 м, 1.1 м, 1.2 м, 1.3 м, 1.6 м, 1.7 м, 1.8 м",
      "Можно установить на ровную площадку во дворе, на даче или рядом с террасой",
      "Подключается фильтрация для поддержания чистоты воды",
      "Ремкомплект и консультация по установке доступны при заказе",
      "Доставка по Казахстану и быстрый заказ через WhatsApp"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Круглый бассейн IPOOLGO, диаметр 3,96 м",
    "price": 180000,
    "old_price": null,
    "article": "R-396",
    "category": "Круглые бассейны",
    "image": "assets/ipoolgoo_best/round_premium_04.webp",
    "gallery": [
      "assets/ipoolgoo_best/round_premium_04.webp",
      "assets/ipoolgoo_best/round_premium_05.webp",
      "assets/ipoolgoo_best/round_premium_06.webp",
      "assets/ipoolgoo_best/round_premium_07.webp",
      "assets/ipoolgoo_best/round_premium_08.webp",
      "assets/ipoolgoo_best/round_premium_09.webp",
      "assets/ipoolgoo_best/round_premium_10.webp",
      "assets/ipoolgoo_best/round_premium_01.webp",
      "assets/ipoolgoo_best/round_premium_02.webp",
      "assets/ipoolgoo_best/round_premium_03.webp"
    ],
    "size": "Ø 3,96 м",
    "form": "Круглая",
    "depth": "на выбор: 1 м / 1.1 м / 1.2 м / 1.3 м / 1.6 м / 1.7 м / 1.8 м",
    "desc": "Круглый бассейн IPOOLGO диаметром Ø 3,96 м — удобное решение для частного дома, дачи или зоны отдыха. Круглая форма равномерно распределяет давление воды на стенки, поэтому чаша устойчиво держит форму при активном купании. Материал ПВХ по технологии Drop Stitch делает борта плотными и жёсткими, а установку можно выполнить без капитального строительства. Цена от 180 000 ₸.",
    "features": [
      "ПВХ по технологии Drop Stitch — плотные борта и устойчивая форма чаши",
      "Глубина на выбор: 1 м, 1.1 м, 1.2 м, 1.3 м, 1.6 м, 1.7 м, 1.8 м",
      "Можно установить на ровную площадку во дворе, на даче или рядом с террасой",
      "Подключается фильтрация для поддержания чистоты воды",
      "Ремкомплект и консультация по установке доступны при заказе",
      "Доставка по Казахстану и быстрый заказ через WhatsApp"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Круглый бассейн IPOOLGO, диаметр 4,27 м",
    "price": 220000,
    "old_price": null,
    "article": "R-427",
    "category": "Круглые бассейны",
    "image": "assets/ipoolgoo_best/round_premium_05.webp",
    "gallery": [
      "assets/ipoolgoo_best/round_premium_05.webp",
      "assets/ipoolgoo_best/round_premium_06.webp",
      "assets/ipoolgoo_best/round_premium_07.webp",
      "assets/ipoolgoo_best/round_premium_08.webp",
      "assets/ipoolgoo_best/round_premium_09.webp",
      "assets/ipoolgoo_best/round_premium_10.webp",
      "assets/ipoolgoo_best/round_premium_01.webp",
      "assets/ipoolgoo_best/round_premium_02.webp",
      "assets/ipoolgoo_best/round_premium_03.webp",
      "assets/ipoolgoo_best/round_premium_04.webp"
    ],
    "size": "Ø 4,27 м",
    "form": "Круглая",
    "depth": "на выбор: 1 м / 1.1 м / 1.2 м / 1.3 м / 1.6 м / 1.7 м / 1.8 м",
    "desc": "Круглый бассейн IPOOLGO диаметром Ø 4,27 м — удобное решение для частного дома, дачи или зоны отдыха. Круглая форма равномерно распределяет давление воды на стенки, поэтому чаша устойчиво держит форму при активном купании. Материал ПВХ по технологии Drop Stitch делает борта плотными и жёсткими, а установку можно выполнить без капитального строительства. Цена от 220 000 ₸.",
    "features": [
      "ПВХ по технологии Drop Stitch — плотные борта и устойчивая форма чаши",
      "Глубина на выбор: 1 м, 1.1 м, 1.2 м, 1.3 м, 1.6 м, 1.7 м, 1.8 м",
      "Можно установить на ровную площадку во дворе, на даче или рядом с террасой",
      "Подключается фильтрация для поддержания чистоты воды",
      "Ремкомплект и консультация по установке доступны при заказе",
      "Доставка по Казахстану и быстрый заказ через WhatsApp"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Круглый бассейн IPOOLGO, диаметр 4,57 м",
    "price": 260000,
    "old_price": null,
    "article": "R-457",
    "category": "Круглые бассейны",
    "image": "assets/ipoolgoo_best/round_premium_06.webp",
    "gallery": [
      "assets/ipoolgoo_best/round_premium_06.webp",
      "assets/ipoolgoo_best/round_premium_07.webp",
      "assets/ipoolgoo_best/round_premium_08.webp",
      "assets/ipoolgoo_best/round_premium_09.webp",
      "assets/ipoolgoo_best/round_premium_10.webp",
      "assets/ipoolgoo_best/round_premium_01.webp",
      "assets/ipoolgoo_best/round_premium_02.webp",
      "assets/ipoolgoo_best/round_premium_03.webp",
      "assets/ipoolgoo_best/round_premium_04.webp",
      "assets/ipoolgoo_best/round_premium_05.webp"
    ],
    "size": "Ø 4,57 м",
    "form": "Круглая",
    "depth": "на выбор: 1 м / 1.1 м / 1.2 м / 1.3 м / 1.6 м / 1.7 м / 1.8 м",
    "desc": "Круглый бассейн IPOOLGO диаметром Ø 4,57 м — удобное решение для частного дома, дачи или зоны отдыха. Круглая форма равномерно распределяет давление воды на стенки, поэтому чаша устойчиво держит форму при активном купании. Материал ПВХ по технологии Drop Stitch делает борта плотными и жёсткими, а установку можно выполнить без капитального строительства. Цена от 260 000 ₸.",
    "features": [
      "ПВХ по технологии Drop Stitch — плотные борта и устойчивая форма чаши",
      "Глубина на выбор: 1 м, 1.1 м, 1.2 м, 1.3 м, 1.6 м, 1.7 м, 1.8 м",
      "Можно установить на ровную площадку во дворе, на даче или рядом с террасой",
      "Подключается фильтрация для поддержания чистоты воды",
      "Ремкомплект и консультация по установке доступны при заказе",
      "Доставка по Казахстану и быстрый заказ через WhatsApp"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Круглый бассейн IPOOLGO, диаметр 4,88 м",
    "price": 300000,
    "old_price": null,
    "article": "R-488",
    "category": "Круглые бассейны",
    "image": "assets/ipoolgoo_best/round_premium_07.webp",
    "gallery": [
      "assets/ipoolgoo_best/round_premium_07.webp",
      "assets/ipoolgoo_best/round_premium_08.webp",
      "assets/ipoolgoo_best/round_premium_09.webp",
      "assets/ipoolgoo_best/round_premium_10.webp",
      "assets/ipoolgoo_best/round_premium_01.webp",
      "assets/ipoolgoo_best/round_premium_02.webp",
      "assets/ipoolgoo_best/round_premium_03.webp",
      "assets/ipoolgoo_best/round_premium_04.webp",
      "assets/ipoolgoo_best/round_premium_05.webp",
      "assets/ipoolgoo_best/round_premium_06.webp"
    ],
    "size": "Ø 4,88 м",
    "form": "Круглая",
    "depth": "на выбор: 1 м / 1.1 м / 1.2 м / 1.3 м / 1.6 м / 1.7 м / 1.8 м",
    "desc": "Круглый бассейн IPOOLGO диаметром Ø 4,88 м — удобное решение для частного дома, дачи или зоны отдыха. Круглая форма равномерно распределяет давление воды на стенки, поэтому чаша устойчиво держит форму при активном купании. Материал ПВХ по технологии Drop Stitch делает борта плотными и жёсткими, а установку можно выполнить без капитального строительства. Цена от 300 000 ₸.",
    "features": [
      "ПВХ по технологии Drop Stitch — плотные борта и устойчивая форма чаши",
      "Глубина на выбор: 1 м, 1.1 м, 1.2 м, 1.3 м, 1.6 м, 1.7 м, 1.8 м",
      "Можно установить на ровную площадку во дворе, на даче или рядом с террасой",
      "Подключается фильтрация для поддержания чистоты воды",
      "Ремкомплект и консультация по установке доступны при заказе",
      "Доставка по Казахстану и быстрый заказ через WhatsApp"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Круглый бассейн IPOOLGO, диаметр 5,49 м",
    "price": 350000,
    "old_price": null,
    "article": "R-549",
    "category": "Круглые бассейны",
    "image": "assets/ipoolgoo_best/round_premium_08.webp",
    "gallery": [
      "assets/ipoolgoo_best/round_premium_08.webp",
      "assets/ipoolgoo_best/round_premium_09.webp",
      "assets/ipoolgoo_best/round_premium_10.webp",
      "assets/ipoolgoo_best/round_premium_01.webp",
      "assets/ipoolgoo_best/round_premium_02.webp",
      "assets/ipoolgoo_best/round_premium_03.webp",
      "assets/ipoolgoo_best/round_premium_04.webp",
      "assets/ipoolgoo_best/round_premium_05.webp",
      "assets/ipoolgoo_best/round_premium_06.webp",
      "assets/ipoolgoo_best/round_premium_07.webp"
    ],
    "size": "Ø 5,49 м",
    "form": "Круглая",
    "depth": "на выбор: 1 м / 1.1 м / 1.2 м / 1.3 м / 1.6 м / 1.7 м / 1.8 м",
    "desc": "Круглый бассейн IPOOLGO диаметром Ø 5,49 м — удобное решение для частного дома, дачи или зоны отдыха. Круглая форма равномерно распределяет давление воды на стенки, поэтому чаша устойчиво держит форму при активном купании. Материал ПВХ по технологии Drop Stitch делает борта плотными и жёсткими, а установку можно выполнить без капитального строительства. Цена от 350 000 ₸.",
    "features": [
      "ПВХ по технологии Drop Stitch — плотные борта и устойчивая форма чаши",
      "Глубина на выбор: 1 м, 1.1 м, 1.2 м, 1.3 м, 1.6 м, 1.7 м, 1.8 м",
      "Можно установить на ровную площадку во дворе, на даче или рядом с террасой",
      "Подключается фильтрация для поддержания чистоты воды",
      "Ремкомплект и консультация по установке доступны при заказе",
      "Доставка по Казахстану и быстрый заказ через WhatsApp"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Прямоугольный бассейн IPOOLGO, размер 2 × 3 × 1,0 м",
    "price": 100000,
    "old_price": null,
    "article": "S-230",
    "category": "Прямоугольные бассейны",
    "image": "assets/ipoolgoo_best/rect_premium_01.jpg",
    "gallery": [
      "assets/ipoolgoo_best/rect_premium_01.jpg",
      "assets/ipoolgoo_best/rect_premium_02.webp",
      "assets/ipoolgoo_best/rect_premium_03.webp",
      "assets/ipoolgoo_best/rect_premium_04.webp",
      "assets/ipoolgoo_best/rect_premium_05.webp",
      "assets/ipoolgoo_best/rect_premium_06.webp",
      "assets/ipoolgoo_best/rect_premium_07.webp",
      "assets/ipoolgoo_best/rect_premium_08.jpg",
      "assets/ipoolgoo_best/rect_premium_09.webp",
      "assets/ipoolgoo_best/rect_premium_10.webp"
    ],
    "size": "2 × 3 × 1,0 м",
    "form": "Прямоугольная",
    "depth": "по выбранному размеру",
    "desc": "Прямоугольный бассейн IPOOLGO размером 2 × 3 × 1,0 м — практичный формат для участка, террасы, бани или загородного дома. Прямоугольная форма помогает рационально использовать место и визуально красиво вписать бассейн вдоль настила, дорожек или зоны отдыха. Чаша изготовлена из прочного ПВХ по технологии Drop Stitch, подходит для сезонной эксплуатации и быстро готовится к работе. Цена от 100 000 ₸.",
    "features": [
      "Прямоугольная форма удобно встаёт вдоль дома, террасы или дорожек",
      "ПВХ по технологии Drop Stitch — жёсткие борта без металлического каркаса",
      "Подходит для семейного отдыха, бани, дачи и гостевых зон",
      "Можно оформить рядом с деревянным настилом или частично углубить после консультации",
      "Подключается насос и фильтрация для регулярного ухода за водой",
      "Доставка по Казахстану и помощь с подбором комплекта"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Прямоугольный бассейн IPOOLGO, размер 2 × 4 × 1,0 м",
    "price": 150000,
    "old_price": null,
    "article": "S-240",
    "category": "Прямоугольные бассейны",
    "image": "assets/ipoolgoo_best/rect_premium_02.webp",
    "gallery": [
      "assets/ipoolgoo_best/rect_premium_02.webp",
      "assets/ipoolgoo_best/rect_premium_03.webp",
      "assets/ipoolgoo_best/rect_premium_04.webp",
      "assets/ipoolgoo_best/rect_premium_05.webp",
      "assets/ipoolgoo_best/rect_premium_06.webp",
      "assets/ipoolgoo_best/rect_premium_07.webp",
      "assets/ipoolgoo_best/rect_premium_08.jpg",
      "assets/ipoolgoo_best/rect_premium_09.webp",
      "assets/ipoolgoo_best/rect_premium_10.webp",
      "assets/ipoolgoo_best/rect_premium_01.jpg"
    ],
    "size": "2 × 4 × 1,0 м",
    "form": "Прямоугольная",
    "depth": "по выбранному размеру",
    "desc": "Прямоугольный бассейн IPOOLGO размером 2 × 4 × 1,0 м — практичный формат для участка, террасы, бани или загородного дома. Прямоугольная форма помогает рационально использовать место и визуально красиво вписать бассейн вдоль настила, дорожек или зоны отдыха. Чаша изготовлена из прочного ПВХ по технологии Drop Stitch, подходит для сезонной эксплуатации и быстро готовится к работе. Цена от 150 000 ₸.",
    "features": [
      "Прямоугольная форма удобно встаёт вдоль дома, террасы или дорожек",
      "ПВХ по технологии Drop Stitch — жёсткие борта без металлического каркаса",
      "Подходит для семейного отдыха, бани, дачи и гостевых зон",
      "Можно оформить рядом с деревянным настилом или частично углубить после консультации",
      "Подключается насос и фильтрация для регулярного ухода за водой",
      "Доставка по Казахстану и помощь с подбором комплекта"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Прямоугольный бассейн IPOOLGO, размер 2 × 5 × 1,2 м",
    "price": 200000,
    "old_price": null,
    "article": "S-2512",
    "category": "Прямоугольные бассейны",
    "image": "assets/ipoolgoo_best/rect_premium_03.webp",
    "gallery": [
      "assets/ipoolgoo_best/rect_premium_03.webp",
      "assets/ipoolgoo_best/rect_premium_04.webp",
      "assets/ipoolgoo_best/rect_premium_05.webp",
      "assets/ipoolgoo_best/rect_premium_06.webp",
      "assets/ipoolgoo_best/rect_premium_07.webp",
      "assets/ipoolgoo_best/rect_premium_08.jpg",
      "assets/ipoolgoo_best/rect_premium_09.webp",
      "assets/ipoolgoo_best/rect_premium_10.webp",
      "assets/ipoolgoo_best/rect_premium_01.jpg",
      "assets/ipoolgoo_best/rect_premium_02.webp"
    ],
    "size": "2 × 5 × 1,2 м",
    "form": "Прямоугольная",
    "depth": "по выбранному размеру",
    "desc": "Прямоугольный бассейн IPOOLGO размером 2 × 5 × 1,2 м — практичный формат для участка, террасы, бани или загородного дома. Прямоугольная форма помогает рационально использовать место и визуально красиво вписать бассейн вдоль настила, дорожек или зоны отдыха. Чаша изготовлена из прочного ПВХ по технологии Drop Stitch, подходит для сезонной эксплуатации и быстро готовится к работе. Цена от 200 000 ₸.",
    "features": [
      "Прямоугольная форма удобно встаёт вдоль дома, террасы или дорожек",
      "ПВХ по технологии Drop Stitch — жёсткие борта без металлического каркаса",
      "Подходит для семейного отдыха, бани, дачи и гостевых зон",
      "Можно оформить рядом с деревянным настилом или частично углубить после консультации",
      "Подключается насос и фильтрация для регулярного ухода за водой",
      "Доставка по Казахстану и помощь с подбором комплекта"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Прямоугольный бассейн IPOOLGO, размер 2 × 6 × 1,2 м",
    "price": 250000,
    "old_price": null,
    "article": "S-2612",
    "category": "Прямоугольные бассейны",
    "image": "assets/ipoolgoo_best/rect_premium_04.webp",
    "gallery": [
      "assets/ipoolgoo_best/rect_premium_04.webp",
      "assets/ipoolgoo_best/rect_premium_05.webp",
      "assets/ipoolgoo_best/rect_premium_06.webp",
      "assets/ipoolgoo_best/rect_premium_07.webp",
      "assets/ipoolgoo_best/rect_premium_08.jpg",
      "assets/ipoolgoo_best/rect_premium_09.webp",
      "assets/ipoolgoo_best/rect_premium_10.webp",
      "assets/ipoolgoo_best/rect_premium_01.jpg",
      "assets/ipoolgoo_best/rect_premium_02.webp",
      "assets/ipoolgoo_best/rect_premium_03.webp"
    ],
    "size": "2 × 6 × 1,2 м",
    "form": "Прямоугольная",
    "depth": "по выбранному размеру",
    "desc": "Прямоугольный бассейн IPOOLGO размером 2 × 6 × 1,2 м — практичный формат для участка, террасы, бани или загородного дома. Прямоугольная форма помогает рационально использовать место и визуально красиво вписать бассейн вдоль настила, дорожек или зоны отдыха. Чаша изготовлена из прочного ПВХ по технологии Drop Stitch, подходит для сезонной эксплуатации и быстро готовится к работе. Цена от 250 000 ₸.",
    "features": [
      "Прямоугольная форма удобно встаёт вдоль дома, террасы или дорожек",
      "ПВХ по технологии Drop Stitch — жёсткие борта без металлического каркаса",
      "Подходит для семейного отдыха, бани, дачи и гостевых зон",
      "Можно оформить рядом с деревянным настилом или частично углубить после консультации",
      "Подключается насос и фильтрация для регулярного ухода за водой",
      "Доставка по Казахстану и помощь с подбором комплекта"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Прямоугольный бассейн IPOOLGO, размер 3 × 6 × 1,4 м",
    "price": 300000,
    "old_price": null,
    "article": "S-3614",
    "category": "Прямоугольные бассейны",
    "image": "assets/ipoolgoo_best/rect_premium_05.webp",
    "gallery": [
      "assets/ipoolgoo_best/rect_premium_05.webp",
      "assets/ipoolgoo_best/rect_premium_06.webp",
      "assets/ipoolgoo_best/rect_premium_07.webp",
      "assets/ipoolgoo_best/rect_premium_08.jpg",
      "assets/ipoolgoo_best/rect_premium_09.webp",
      "assets/ipoolgoo_best/rect_premium_10.webp",
      "assets/ipoolgoo_best/rect_premium_01.jpg",
      "assets/ipoolgoo_best/rect_premium_02.webp",
      "assets/ipoolgoo_best/rect_premium_03.webp",
      "assets/ipoolgoo_best/rect_premium_04.webp"
    ],
    "size": "3 × 6 × 1,4 м",
    "form": "Прямоугольная",
    "depth": "по выбранному размеру",
    "desc": "Прямоугольный бассейн IPOOLGO размером 3 × 6 × 1,4 м — практичный формат для участка, террасы, бани или загородного дома. Прямоугольная форма помогает рационально использовать место и визуально красиво вписать бассейн вдоль настила, дорожек или зоны отдыха. Чаша изготовлена из прочного ПВХ по технологии Drop Stitch, подходит для сезонной эксплуатации и быстро готовится к работе. Цена от 300 000 ₸.",
    "features": [
      "Прямоугольная форма удобно встаёт вдоль дома, террасы или дорожек",
      "ПВХ по технологии Drop Stitch — жёсткие борта без металлического каркаса",
      "Подходит для семейного отдыха, бани, дачи и гостевых зон",
      "Можно оформить рядом с деревянным настилом или частично углубить после консультации",
      "Подключается насос и фильтрация для регулярного ухода за водой",
      "Доставка по Казахстану и помощь с подбором комплекта"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Прямоугольный бассейн IPOOLGO, размер 4 × 6 × 1,4 м",
    "price": 350000,
    "old_price": null,
    "article": "S-4614",
    "category": "Прямоугольные бассейны",
    "image": "assets/ipoolgoo_best/rect_premium_06.webp",
    "gallery": [
      "assets/ipoolgoo_best/rect_premium_06.webp",
      "assets/ipoolgoo_best/rect_premium_07.webp",
      "assets/ipoolgoo_best/rect_premium_08.jpg",
      "assets/ipoolgoo_best/rect_premium_09.webp",
      "assets/ipoolgoo_best/rect_premium_10.webp",
      "assets/ipoolgoo_best/rect_premium_01.jpg",
      "assets/ipoolgoo_best/rect_premium_02.webp",
      "assets/ipoolgoo_best/rect_premium_03.webp",
      "assets/ipoolgoo_best/rect_premium_04.webp",
      "assets/ipoolgoo_best/rect_premium_05.webp"
    ],
    "size": "4 × 6 × 1,4 м",
    "form": "Прямоугольная",
    "depth": "по выбранному размеру",
    "desc": "Прямоугольный бассейн IPOOLGO размером 4 × 6 × 1,4 м — практичный формат для участка, террасы, бани или загородного дома. Прямоугольная форма помогает рационально использовать место и визуально красиво вписать бассейн вдоль настила, дорожек или зоны отдыха. Чаша изготовлена из прочного ПВХ по технологии Drop Stitch, подходит для сезонной эксплуатации и быстро готовится к работе. Цена от 350 000 ₸.",
    "features": [
      "Прямоугольная форма удобно встаёт вдоль дома, террасы или дорожек",
      "ПВХ по технологии Drop Stitch — жёсткие борта без металлического каркаса",
      "Подходит для семейного отдыха, бани, дачи и гостевых зон",
      "Можно оформить рядом с деревянным настилом или частично углубить после консультации",
      "Подключается насос и фильтрация для регулярного ухода за водой",
      "Доставка по Казахстану и помощь с подбором комплекта"
    ],
    "material": "ПВХ / Drop Stitch",
    "warranty": "12 месяцев",
    "thermo": "от -20°C до +80°C",
    "install_time": "20–30 минут"
  },
  {
    "title": "Зимнее защитное накрытие для бассейнов IPOOLGO, диаметр 3 м",
    "price": 0,
    "old_price": 0,
    "uah": 0,
    "article": "AP-02",
    "category": "Аксессуары",
    "image": "assets/images/p003_b76ab8.webp",
    "gallery": [
      "assets/images/p003_b76ab8.webp",
      "assets/galleries/AP-02_1.webp",
      "assets/galleries/AP-02_2.webp",
      "assets/galleries/AP-02_3.png",
      "assets/galleries/AP-02_4.png",
      "assets/galleries/AP-02_5.png",
      "assets/galleries/AP-02_6.webp"
    ],
    "size": "",
    "desc": "Защитное накрытие помогает закрыть бассейн от мусора, листьев и осадков. Совместимость по размеру уточнит менеджер.",
    "features": [
      "Доставка по Казахстану",
      "Менеджер подскажет совместимость",
      "Можно добавить к заказу вместе с бассейном"
    ]
  },
  {
    "title": "Фильтрационная установка Emaux FSU-8TP, 8 м³/ч, D300",
    "price": 0,
    "old_price": 0,
    "uah": 0,
    "article": "filtracziya-profi",
    "category": "Насосы и фильтры",
    "image": "assets/images/p013_5377d2.webp",
    "gallery": [
      "assets/images/p013_5377d2.webp",
      "assets/galleries/filtracziya-profi_1.webp",
      "assets/galleries/filtracziya-profi_2.webp"
    ],
    "size": "",
    "desc": "Фильтрационная установка для поддержания чистоты воды в бассейне.",
    "features": [
      "Доставка по Казахстану",
      "Менеджер подскажет совместимость",
      "Можно добавить к заказу вместе с бассейном"
    ]
  },
  {
    "title": "Электрический насос IPOOLGO Intelligent DC Electric Pump IP 790",
    "price": 0,
    "old_price": 0,
    "uah": 0,
    "article": "AP-01",
    "category": "Насосы и фильтры",
    "image": "assets/images/p016_fca8df.webp",
    "gallery": [
      "assets/images/p016_fca8df.webp",
      "assets/galleries/AP-01_1.webp",
      "assets/galleries/AP-01_2.webp",
      "assets/galleries/AP-01_3.webp",
      "assets/galleries/AP-01_4.webp",
      "assets/galleries/AP-01_5.webp",
      "assets/galleries/AP-01_6.webp"
    ],
    "size": "",
    "desc": "Электрический насос для быстрого надувания бассейна и удобной подготовки к эксплуатации.",
    "features": [
      "Доставка по Казахстану",
      "Менеджер подскажет совместимость",
      "Можно добавить к заказу вместе с бассейном"
    ]
  },
  {
    "title": "Фильтрационная установка Bestway FlowClear 58497, 5.6 м³/ч, D254",
    "price": 0,
    "old_price": 0,
    "uah": 0,
    "article": "filtracziya-standart",
    "category": "Насосы и фильтры",
    "image": "assets/images/p017_2addee.webp",
    "gallery": [
      "assets/images/p017_2addee.webp",
      "assets/galleries/filtracziya-standart_1.webp",
      "assets/galleries/filtracziya-standart_2.webp"
    ],
    "size": "",
    "desc": "Фильтр для ежедневной очистки воды и комфортной эксплуатации бассейна.",
    "features": [
      "Доставка по Казахстану",
      "Менеджер подскажет совместимость",
      "Можно добавить к заказу вместе с бассейном"
    ]
  }
];
